version: "3"

services:
    reverse-proxy:
        # The official v3 Traefik docker image
        image: traefik:v3.0
        # Enables the web UI and tells Traefik to listen to docker
        command:
            - "--providers.swarm=true"
            - "--entryPoints.web.address=:80"
        ports:
            - "80:80"
        deploy:
            placement:
                constraints:
                    - node.role == manager
            labels:
                - "traefik.http.services.app.loadbalancer.server.port=80"

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    web:
        image: app
        build: .
        deploy:
            labels:
                - "traefik.http.routers.router1.entryPoints=web"
                - "traefik.http.routers.router1.rule=Path(`/hello-world`)"
                - "traefik.http.routers.router1.service=service1"
                - "traefik.http.services.service1.loadbalancer.server.port=5000"
